language: python
sudo: false
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- |
  if [ "$TEST_TYPE" = build ]; then
    pip install -e .[test]
    python setup.py develop
  elif [ "$TEST_TYPE" = lint ]; then
    pip install flake8
  fi
script:
- |
  if [ "$TEST_TYPE" = lint ]; then
    echo "Checking Python code lint."
    flake8 graphene_tornado
    exit
  elif [ "$TEST_TYPE" = build ]; then
    py.test --cov=graphene_tornado graphene_tornado examples
  fi
after_success:
- |
  if [ "$TEST_TYPE" = build ]; then
      coveralls
  fi
env:
  matrix:
  - TEST_TYPE=build
matrix:
  fast_finish: true
  include:
  - python: '2.7'
    env: TEST_TYPE=build
  - python: '3.4'
    env: TEST_TYPE=build
  - python: '3.5'
    env: TEST_TYPE=build
  - python: '3.6'
    env: TEST_TYPE=build
  - python: '3.7'
    env: TEST_TYPE=build
  - python: '2.7'
    env: TEST_TYPE=lint
  - python: '3.7'
    env: TEST_TYPE=lint
